### ISSUE TITLE
ethertype is modified from 88a8 to 8100

### ISSUE THREAD

**Issue by BabisK** [CPqD/ofsoftswitch13#179]
I'm using Ubuntu 14.04.01 with latest mininet and ofsoftswitch

I create with mininet a topology like this:
h1 - s1 - s2 - h2

On s1 I insert a flow that matches all frames from h1, adds a CVLAN (ethertype 8100, ID 79) and a SVLAN (ethertype 88a8, ID 100) and sends it to s2. Here's the flow in s1 from dpctl:

{table="0", match="oxm{in_port="1"}", dur_s="8460", dur_ns="861000", prio="10", idle_to="0", hard_to="0", cookie="0x0", pkt_cnt="0", byte_cnt="0", insts=[apply{acts=[vlan_psh{eth="0x8100"}, set_field{field:vlan_vid="79"}, vlan_psh{eth="0x88a8"}, set_field{field:vlan_vid="100"}, out{port="2"}]}]}

I ping from h1 to h2. I have put wireshark on the port of s1 that connects to s2 and on the port of s2 that connects to s1. The frame that leaves s1 has 2 VLAN tags, one with ethertype 88a8 and a second one with ethertype 8100. Everything is as expected. But s2 receives a frame with 2 VLAN tags, both of them have ethertype 8100. So something between s1 and s2 modified the first ethertype from 88a8 to 8100.

Frame coming out of s1: 
6abe6b6290b576294e3bb985**88a8**00648100004f0800450000548758400040019f4e0a0000010a00000208008f200f3400012e5f6455000000000723010000000000101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637

Frame going into s2:
6abe6b6290b576294e3bb985**8100**00648100004f0800450000548758400040019f4e0a0000010a00000208008f200f3400012e5f6455000000000723010000000000101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637

The hex in bold are the only difference between those two. Is this a bug in ofsoftswitch or should I look elsewhere in my system?

**Comment by ederlf** [comment]
Hi, it is not a switch problem.

When the a VLAN tagged packet arrive at the switch the kernel strips the tag,. Because of this we reconstruct the header in the switch after the packet arrival on the userspace. 

Wireshark probably does not reconstruct the packet (which makes sense, because it is just a dissector) 
 
To check it, add a flow in s2
sudo dpctl unix:/tmp/s2 flow-mod table=0 in_port=1 apply:output=2

Then sent packets from s1 to s2 and verify the s2-eth2 interface. You shall see the correct packet.
