### ISSUE TITLE
ofsoftswitch13 supports LLDP and BDDP packets?

### ISSUE THREAD

**Issue by maury89** [CPqD/ofsoftswitch13#229]
Hi to everyone.
My question is the following: I need to use LLDP and BDDP (i.e. Broadcast Domain Discovery Protocol to discover switches in different domain) protocols for my thesis.
Ofsoftswitch13 support these protocols? 
Thanks.
Maurizio

**Comment by ederlf** [comment]
What do you mean by support? Matching on LLDP and BDDP fields? If that is the case, not. Also, there is no implementation of the functionality of those protocols, since the switch is purely OpenFlow.

Now if you want to use those packets for some kind of discovery in SDN, you need to implement some logic to make them reach the switch ports and then be sent to the controller, so it can map the topology links.
