### ISSUE TITLE
Just a thought (not an issue, but important anyway)

### ISSUE THREAD

**Issue by ElisaRojas** [CPqD/ofsoftswitch13#248]
Hi!

This is just a thought for the authors of CPqD's ofsoftswitch13. Although the development is a bit old, this software switch is still leveraged in many places, for example, I have used it to create custom SDN switches (it is easier than modifying OvS, though the performance is not the best... but for PoCs is great) or to test QinQ capabilities (which are not supported by OvS). 

So, I was wondering, why not giving it more visibility? Every time I need to reference this switch, it doesn't even have a name, so I call it "CPqD's switch" :smile: and cite it with the GitHub URL, but it would super nice to have some document/paper (even if it is not published by important journals -> arXiV could be ok). 
In this way, some people could be willing to help to its development (because, believe, this switch is still useful, even when it's so old...) and to improve it (fixing bugs, etc.).

What do you think? :smiley: As I said... not an issue, just a thought!

Thank you!

**Comment by ederlf** [comment]
Hi Elisa, your thoughts are more than welcome :-)

> This is just a thought for the authors of CPqD's ofsoftswitch13. Although the development is a bit old, this software switch is still leveraged in many places, for example, I have used it to create custom SDN switches (it is easier than modifying OvS, though the performance is not the best... but for PoCs is great) or to test QinQ capabilities (which are not supported by OvS).

That is exactly the whole point of the software switch. While OVS is what I consider the de facto switch for OpenFlow it is not simple enough to extend.  So whenever you need to add your extensions to OpenFlow or any other mechanism, SDN or not, the switch is there for it.

> So, I was wondering, why not giving it more visibility? Every time I need to reference this switch, it doesn't even have a name, so I call it "CPqD's switch" :smile: and cite it with the GitHub URL, but it would super nice to have some document/paper (even if it is not published by important journals -> arXiV could be ok).
In this way, some people could be willing to help to its development (because, believe, this switch is still useful, even when it's so old...) and to improve it (fixing bugs, etc.).

It would be amazing to have more visibility. When I look at statistics of views and clones it still has almost the same number when the development was constant. Also every month people send me questions (and bug reports, always)  about it. (vary from experiences like trying to run it on a raspberry pi to just how add experimenter fields).

I agree to the point that there is need to have a publication. At the time we only published it in [Portuguese on a Brazilian conference](http://www.sbrc2014.ufsc.br/anais/files/salao/SF-ST3-1.pdf), and I also used it to my [master's thesis](http://repositorio.unicamp.br/bitstream/REPOSIP/258850/1/Fernandes%2c%20Eder%20Leao_M.pdf). It was enough to finish my masters but I had always the feeling it was not enough.

All said, you gave an idea. What about a paper about the software switch but also including the prototyping experiences? So it would not be just a paper describing the switch but something that show the importance of having basic tools that can be hacked by researchers wanting to proof a concept.

Would you be willing to contribute? I already have a journal in mind (SIGCOMM CCR seems the best match) , but I am happy to discuss :-). In case it does not go though, I am happy to have it on arXiV too.

Thank you.

**Comment by ElisaRojas** [comment]
Hi @ederlf !

I'm glad to read your response! Yes, a publication in some recognized journal would be the icing on the cake :smile: I knew the publication in Portuguese, but one in English (apart from your thesis) would be nice to have. And I think your idea of including prototyping experiences is really good! So I'll be glad to help.

Currently, we have this publication of a hybrid SDN switch based on ofsoftswitch13:
[New cooperative mechanisms for software defined networks based on hybrid switches](http://onlinelibrary.wiley.com/doi/10.1002/ett.3150/abstract )
We could include our experiences based on the development (the paper is more related to the hybrid feature than the technical implementation).

In my team, we have also used CPqD's switch to test CORD (ONOS' use case), because it requires QinQ capabilities. And I also teach the switch in [this SDN&NFV master](http://www.uc3m.es/ss/Satellite/Postgrado/en/Detalle/Estudio_C/1371215129087/1371219633369/Master_and_Specialist_in_NFV_and_SDN) degree: 
Any of these could be good examples as well.

I'll be glad to help contributing the paper, so count me in! :smiley: I might need somebody else from my team to join and contribute as well, if that's ok. 
Regarding journals, SIGCOMM CCR is a good one. Do you plan to submit to the conference or directly to the journal? This could also be an option: http://www.comsoc.org/jsac/series/netsoft-enablers (although CFP are usually harder). In case it does not go through, arXiV is also ok as you mention.

Ok, so that's all so far... Please contact me via email and we can start preparing the paper as soon as you want.

Thank you!

**Comment by ederlf** [comment]
Hi @ElisaRojas,

> Currently, we have this publication of a hybrid SDN switch based on ofsoftswitch13:
New cooperative mechanisms for software defined networks based on hybrid switches
We could include our experiences based on the development (the paper is more related to the hybrid feature than the technical implementation).
 In my team, we have also used CPqD's switch to test CORD (ONOS' use case), because it requires QinQ capabilities. And I also teach the switch in this SDN&NFV master degree:
Any of these could be good examples as well.

It all sounds great :-)

> I'll be glad to help contributing the paper, so count me in! :smiley: I might need somebody else from my team to join and contribute as well, if that's ok.

Sure, any additional contributor is welcome.

> Regarding journals, SIGCOMM CCR is a good one. Do you plan to submit to the conference or directly to the journal? This could also be an option: http://www.comsoc.org/jsac/series/netsoft-enablers (although CFP are usually harder). In case it does not go through, arXiV is also ok as you mention.

I would go to directly to the CCR journal. Another possibility i thought is a magazine like the [ACM Queue](http://queue.acm.org/), but we can discuss it better while we prepare the paper.

I will talk with my former supervisor tomorrow or Tuesday and then I'll start an email thread with you.

Thanks!

**Comment by chesteve** [comment]
Great initiative! Thanks Elisa!! Indeed, an article (at least English-based techreport in arxiv) on the softswitch13 should have been published a long time ago (+3  years). We should be right now on a second publication reporting on the community contributions, enabling research use cases, as well as the support of OpenFlow spec feature prototyping at ONF. As I told Eder, there is still potential for a high impact publication, but it will depend on how much effort (especially Eder as the leader) and how many committed co-authors we are able to gather...

**Comment by nikchez01** [comment]
I have just started working of realization of PON Access network requirements (such BW distribution among thousands of users) using Openflow (with ofsoftswitch13 as POC). May be I can help too.

**Comment by ZoltanLajosKis** [comment]
Also happy to help! Mostly with the historical aspects, I guess. :-D
